-- Seed data for compliance requirements (España)
INSERT INTO compliance_requirements (title, description, category, severity, countries, sectors, company_sizes, is_recurring, frequency, action_steps, estimated_time, links) VALUES
(
  'Depósito de Cuentas Anuales',
  'Las sociedades deben presentar las cuentas anuales en el Registro Mercantil dentro de los 30 días siguientes a su aprobación',
  'contabilidad',
  'high',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['micro', 'small', 'medium'],
  true,
  'annual',
  '{"steps": ["Aprobar cuentas en Junta General", "Legalizar libros contables", "Presentar en Registro Mercantil"]}',
  120,
  '{"registro_mercantil": "https://www.registradores.org/"}'
),
(
  'Modelo 303 - IVA Trimestral',
  'Declaración trimestral del IVA para autónomos y empresas',
  'fiscal',
  'critical',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['micro', 'small', 'medium'],
  true,
  'quarterly',
  '{"steps": ["Calcular IVA devengado", "Calcular IVA soportado", "Presentar modelo 303 en AEAT"]}',
  60,
  '{"aeat": "https://sede.agenciatributaria.gob.es/"}'
),
(
  'RGPD - Registro de Actividades de Tratamiento',
  'Obligatorio mantener un registro de actividades de tratamiento de datos personales',
  'proteccion_datos',
  'high',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['small', 'medium'],
  false,
  null,
  '{"steps": ["Identificar tratamientos de datos", "Documentar finalidades y bases legales", "Crear registro de actividades"]}',
  180,
  '{"aepd": "https://www.aepd.es/"}'
),
(
  'Plan de Igualdad',
  'Empresas de más de 50 trabajadores deben contar con un Plan de Igualdad',
  'laboral',
  'medium',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['small', 'medium'],
  false,
  null,
  '{"steps": ["Constituir comisión negociadora", "Realizar diagnóstico de situación", "Elaborar y registrar plan de igualdad"]}',
  480,
  '{"ministerio": "https://www.igualdadenlaempresa.es/"}'
),
(
  'Modelo 190 - Retenciones IRPF',
  'Resumen anual de retenciones e ingresos a cuenta del IRPF',
  'fiscal',
  'critical',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['micro', 'small', 'medium'],
  true,
  'annual',
  '{"steps": ["Recopilar datos de retenciones", "Validar certificados emitidos", "Presentar modelo 190"]}',
  90,
  '{"aeat": "https://sede.agenciatributaria.gob.es/"}'
);

-- Seed data for grants (España 2024-2026)
INSERT INTO grants (title, description, issuer, countries, sectors, company_sizes, max_amount, funding_type, application_start, application_deadline, is_active, requirements, documents_needed, official_url) VALUES
(
  'Kit Digital 2024',
  'Ayudas para la digitalización de pequeñas empresas, autónomos y microempresas',
  'Red.es - Ministerio de Asuntos Económicos',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['micro', 'small'],
  12000.00,
  'grant',
  '2024-01-15',
  '2026-12-31',
  true,
  '{"requisitos": ["Estar al corriente de obligaciones fiscales", "No superar umbrales de ayudas de minimis", "Contar con Certificado Digital"]}',
  '{"documentos": ["CIF", "Certificado de estar al corriente con AEAT", "Certificado de estar al corriente con Seguridad Social"]}',
  'https://www.acelerapyme.gob.es/kit-digital'
),
(
  'Programa NEOTEC',
  'Ayudas para empresas innovadoras de base tecnológica en fase de creación y expansión',
  'CDTI - Ministerio de Ciencia e Innovación',
  ARRAY['ES'],
  ARRAY['tecnologia', 'industria', 'salud'],
  ARRAY['micro', 'small'],
  250000.00,
  'grant',
  '2024-03-01',
  '2024-12-15',
  true,
  '{"requisitos": ["Antigüedad menor a 2 años", "Base tecnológica", "Plan de negocio innovador"]}',
  '{"documentos": ["Memoria técnica", "Plan de negocio", "Presupuesto detallado", "Cuentas anuales"]}',
  'https://www.cdti.es/neotec'
),
(
  'Bonificaciones por Contratación Indefinida',
  'Bonificaciones en las cuotas de la Seguridad Social por contratación indefinida de ciertos colectivos',
  'Seguridad Social - Ministerio de Trabajo',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['micro', 'small', 'medium'],
  3600.00,
  'tax_credit',
  '2024-01-01',
  '2026-12-31',
  true,
  '{"requisitos": ["Contrato indefinido", "Jornada completa", "No haber tenido reducción de plantilla en 6 meses"]}',
  '{"documentos": ["Contrato de trabajo", "Alta en Seguridad Social", "Certificado de plantilla"]}',
  'https://www.sepe.es/HomeSepe/empresas/informacion-para-empresas/contratos-de-trabajo/bonificaciones.html'
),
(
  'Programa ICEX Next',
  'Ayudas para la internacionalización de pymes españolas',
  'ICEX España Exportación e Inversiones',
  ARRAY['ES'],
  ARRAY['todos'],
  ARRAY['small', 'medium'],
  15000.00,
  'grant',
  '2024-02-01',
  '2024-11-30',
  true,
  '{"requisitos": ["Proyecto de internacionalización definido", "Primera exportación o mercados nuevos", "Facturación mínima 500.000€"]}',
  '{"documentos": ["Plan de internacionalización", "Cuentas anuales", "Declaración de ayudas de minimis"]}',
  'https://www.icex.es/icex/es/navegacion-principal/todos-nuestros-servicios/programas-de-ayudas/icex-next/index.html'
);
